    - name: install TASK
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes