- name: install nginx PALY
  hosts: ALL
  become: true
  tasks:
    - name: install TASK
      ansible.builtin.yum:
        name: httpd
        state: latest

    - name: restart nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes
- name: install nginx PALY2
  hosts: WEB
  become: true
  roles:
      -sample